name: productivityapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.18.1
  path: ^1.8.2
  provider: ^6.0.5
  riverpod_generator: ^2.2.3
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
